### ISSUE TITLE
Adding ember-engines forces live-reload when changing styles

### ISSUE THREAD

**Issue by ilucin** [ember-engines/ember-engines#396]
Steps to reproduce: 
```
ember new testapp
ember install ember-engines
```

When styles are changed live-reload is triggered with debug output:
```
file changed styles/app.css

Build successful (142ms) – Serving on http://localhost:4200/
  ember-cli:live-reload: files %a [ 'assets/debug-styles-hot-reload.css',
  'index.html',
  'tests/index.html' ] +9s
```

I guess `'index.html'` & `'tests/index.html'` shouldn't be there.

Tested on:
ember-cli: 2.13.0-beta.4 & 2.12.2
ember-engines: 0.5.2
node: 7.9.0 & 6.x
os: darwin x64

**Comment by XaserAcheron** [comment]
This is basically a glorified +1, but this has been a thorn in my side since adopting engines. I also did a bunch of other updates at the same time, so I was planning on doing some test app stuff to make sure it was actually ember-engines that was causing this, but seems you've already done so. Thanks!

**Comment by stefanpenner** [comment]
> I guess 'index.html' & 'tests/index.html' shouldn't be there.

Interesting, yes this is most likely hinting at the root cause. Specifically, investigating what ember-engines does to index.html files, and how it is misbehaving.

**Comment by XaserAcheron** [comment]
[disclaimer: non-expert comments follow]

I'm thinking this has to do with the asset manifest meta tag that gets inserted into index.html. See [here](https://github.com/ember-engines/ember-engines/blob/master/index.js), though the more interesting upstream code is in `ember-asset-loader` [here](https://github.com/ember-engines/ember-asset-loader/blob/master/lib/manifest-generator.js).

I haven't fully traced the logic yet (my broccoli-fu is weak), but it seems quite plausible that a (S)CSS change would eventually yield a change to index.html via refreshing the meta tag. If so, it'd be handy to no-op if there's no change there.

**Comment by mfeckie** [comment]
Any update with this folks?

**Comment by rwjblue** [comment]
No, I don’t think anyone has worked on fixing the issue. Also, I believe that https://github.com/ember-engines/ember-asset-loader/issues/49 is a better place to track it...

**Comment by mfeckie** [comment]
Thanks @rwjblue  , I'm taking a look to see if I can help there

**Comment by trentmwillis** [comment]
This should be fixed by https://github.com/ember-engines/ember-engines/pull/492 on the next release.

**Comment by MartinMalinda** [comment]
I'm still seeing this happening with `"ember-engines": "^0.5.14"`. When I change CSS inside the Engine, liveReload gets a message with `asset-manifest.json`, `tests/index.html` `index.html` being changed. It happens for CSS changes in the host application too.

![screen shot 2017-11-10 at 12 03 15](https://user-images.githubusercontent.com/9468793/32655790-6fabf60c-c60f-11e7-92f1-7414cae228b6.png)

**Comment by MartinMalinda** [comment]
I tested this on master and while styles in the host app don't trigger a refresh, styles in the engine still do. Is this expected?

**Comment by MartinMalinda** [comment]
https://github.com/ember-engines/ember-asset-loader/blob/master/lib/asset-manifest-inserter.js#L67

This check does not do prevent refresh in this case, because while one of the index files has info about the bundles, the other one has just `<meta name="aaa/config/asset-manifest" content="%GENERATED_ASSET_MANIFEST%" />`

**Comment by stefanpenner** [comment]
This is still an issue:

VERSIONS:
* ember-cli@2.16.2
* ember-engines@0.5.14


```
DEBUG="ember-cli:live-reload:*" ember s
```

touch some css file

```
Build successful (106ms) – Serving on http://localhost:4200/
  ember-cli:live-reload: files %a [ 'asset-manifest.json',
  'assets/node-asset-manifest.js',
  'engines-dist/lazy/assets/engine.css',
  'index.html',
  'tests/index.html' ] +30s
```

**Comment by rwjblue** [comment]
@stefanpenner - Can you `npm ls ember-asset-loader`?

**Comment by robclancy** [comment]
This issue is fixed when using the current master for me. Just needs a release?

**Comment by villander** [comment]
@stefanpenner can you close this issue, please? It's already fixed

**Comment by sebastianhelbig** [comment]
I still have this problem :-( Anyone has an idea how to debug this?

Changing an scss file inside a lazy loaded engine.
ember-asset-loader: 0.6.1
ember-engines: 0.8.20
ember-source: 3.28.8

>DEBUG="ember-cli:live-reload:*" ember s
> ember-cli:live-reload: files [ 'asset-manifest.json', 'assets/node-asset-manifest.js', 'engines-dist/lazy-engine/assets/engine.css' ] +2m
